import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home | Find The Country</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>home</h1>
      </main>
    </div>
  );
}
